import { NextResponse } from 'next/server';

export const dynamic = 'force-static';

export async function GET() {
  return new NextResponse(`<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://www.fixwheel.app/ghaziabad</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/ghaziabad/abhay-khand</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/ghaziabad/ahinsa-khand</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/ghaziabad/crossings-republik</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/ghaziabad/dasna</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/ghaziabad/dilshad-garden-border</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/ghaziabad/gandhi-nagar</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/ghaziabad/govindpuram</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/ghaziabad/gt-road</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/ghaziabad/hindon</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/ghaziabad/indirapuram</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/ghaziabad/kaushambi</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/ghaziabad/loni</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/ghaziabad/mohan-nagar</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/ghaziabad/nehru-nagar</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/ghaziabad/nh-24</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/ghaziabad/nyay-khand</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/ghaziabad/raj-nagar</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/ghaziabad/raj-nagar-extension</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/ghaziabad/sanjay-nagar</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/ghaziabad/shakti-khand</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/ghaziabad/shastri-nagar</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/ghaziabad/shipra-suncity</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/ghaziabad/surya-nagar</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/ghaziabad/vaishali</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/ghaziabad/vasundhara</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/ghaziabad/vijay-nagar</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>
</urlset>`, {
    headers: {
      'Content-Type': 'application/xml',
      'Cache-Control': 'public, max-age=3600, s-maxage=86400',
    },
  });
}
