import CityPageSections, { type CityPageConfig, type CityPageSectionsProps } from "@/components/city/CityPageSections";

const noidaConfig: CityPageConfig = {
  cityName: "Noida",
  citySlug: "noida",
  hero: {
    eyebrow: "Bike mechanic at your doorstep · Noida",
    title: "Bike Mechanic Near Me",
    emphasis: "in Noida",
    lead: "FixWheel sends verified mechanics directly to your high-rise society, gated sector, or corporate office across Noida & Greater Noida. Forget towing your bike to local garages — we bring the tools and service to you.",
    bookingLabel: "Book a Mechanic in Noida →",
    arrivalTime: "45 min",
    ratingSource: "public-stats",
    serviceArea: "Noida & Gr. Noida",
    ticketId: "FW-NOI-0914",
    ticketRows: [
      { label: "Service", value: "Basic Service" },
      { label: "Model", value: "Honda Activa 6G" },
      { label: "Location", value: "Sector 62, Noida" },
      { label: "Mechanic", value: "Verified ✓" },
      { label: "Warranty", value: "15 days" },
      { label: "Response", value: "27 min" },
    ],
    totalPaid: "₹550",
    ticketRegion: "NOIDA · NCR",
  },
  coverage: {
    description: "We serve all major residential sectors and commercial parks across Noida and Greater Noida. Select your locality below for detailed street coverage.",
    expansionLabel: "📍 + Expanding across Noida",
    areas: [
      { name: "Sector 18", slug: "sector-18" },
      { name: "Sector 22", slug: "sector-22" },
      { name: "Sector 27", slug: "sector-27" },
      { name: "Sector 29", slug: "sector-29" },
      { name: "Sector 37", slug: "sector-37" },
      { name: "Sector 44", slug: "sector-44" },
      { name: "Sector 50", slug: "sector-50" },
      { name: "Sector 51", slug: "sector-51" },
      { name: "Sector 52", slug: "sector-52" },
      { name: "Sector 55", slug: "sector-55" },
      { name: "Sector 56", slug: "sector-56" },
      { name: "Sector 62", slug: "sector-62" },
      { name: "Sector 63", slug: "sector-63" },
      { name: "Sector 75", slug: "sector-75" },
      { name: "Sector 76", slug: "sector-76" },
      { name: "Sector 77", slug: "sector-77" },
      { name: "Sector 78", slug: "sector-78" },
      { name: "Sector 100", slug: "sector-100" },
      { name: "Sector 104", slug: "sector-104" },
      { name: "Sector 110", slug: "sector-110" },
      { name: "Sector 120", slug: "sector-120" },
      { name: "Sector 125", slug: "sector-125" },
      { name: "Sector 126", slug: "sector-126" },
      { name: "Sector 128", slug: "sector-128" },
      { name: "Sector 132", slug: "sector-132" },
      { name: "Sector 135", slug: "sector-135" },
      { name: "Sector 137", slug: "sector-137" },
      { name: "Sector 143", slug: "sector-143" },
      { name: "Sector 150", slug: "sector-150" },
      { name: "Greater Noida West", slug: "greater-noida-west" },
      { name: "Knowledge Park", slug: "knowledge-park" },
      { name: "Alpha 1", slug: "alpha-1" },
      { name: "Alpha 2", slug: "alpha-2" },
      { name: "Omega", slug: "omega" },
      { name: "Chi Phi", slug: "chi-phi" },
      { name: "Techzone 4", slug: "techzone-4" },
      { name: "Noida Extension", slug: "noida-extension" },
    ],
  },
  why: {
    heading: "Professional service right in your society parking",
    description: "High-rise society gates or busy tech parks — our mechanics coordinate directly to service your bike while you work or relax.",
    cards: [
      { title: "Convenient at-home service", text: "Our mechanics carry out the entire service inside your gated society basement, driveway, or office parking slot." },
      { title: "Trained & verified professionals", text: "Every mechanic is background-checked and trained, giving you complete safety and professional mechanical work." },
      { title: "No hidden billing", text: "Upfront itemized quotes before the service begins. You only pay for what you explicitly approve." },
      { title: "15-day labor warranty", text: "All mechanical and electrical adjustments are backed by a solid 15-day service guarantee for complete peace of mind." },
    ],
  },
  how: [
    { title: "1. Pick a service", text: "Select what your bike needs and pick a time slot on our app or website." },
    { title: "2. Mechanic dispatched", text: "A verified mechanic near your location in Noida is assigned and heads to you." },
    { title: "3. Repaired on-site", text: "Your bike is fixed right where it is parked — home, office, or society parking." },
    { title: "4. Pay and rate", text: "Pay the quoted amount via UPI, card, or cash, then rate the mechanic." },
  ],
  reviews: {
    heading: "From Noida riders",
    rating: "4.7★",
    items: [
      { text: "Excellent experience in Sector 137. The mechanic coordinated with the society gate security himself and finished the general service in the basement. Spotless cleanup after service.", author: "Abhishek T. — Sector 137" },
      { text: "My Royal Enfield Bullet broke down near Noida Sector 62. The roadside assistance mechanic was there in 45 minutes, cleaned the carburetor on the spot, and got it started. Highly recommended!", author: "Vikram S. — Sector 62" },
      { text: "Got my TVS Jupiter serviced at home in Greater Noida West. Very polite technician, pre-confirmed pricing, and no pushy upselling.", author: "Pallavi G. — Greater Noida West" },
    ],
  },
  partner: {
    heading: "Are you a bike mechanic in Noida?",
    description: "Join the FixWheel network and receive bookings from riders in Noida and Greater Noida. Set your own hours and manage everything from your phone.",
    registrationText: "Register in a few minutes and start receiving service requests in Noida.",
  },
  faqs: [
    { question: "How quickly can a mechanic reach me in Noida?", answer: "In most Noida sectors, our mechanics arrive within 45 minutes of booking confirmation." },
    { question: "What does doorstep bike repair cost in Noida?", answer: "Basic service starts from ₹550 depending on your bike model. We confirm the exact price before starting any work." },
    { question: "Which areas in Noida does FixWheel cover?", answer: "We cover all major Noida sectors (18, 62, 137, 150, etc.) as well as Greater Noida West, Knowledge Park, and Noida Extension." },
    { question: "Do you offer emergency roadside help in Noida?", answer: "Yes, we dispatch mechanics for roadside breakdowns across our Noida service area. Available 24/7." },
    { question: "Can you service my EV scooter in Noida?", answer: "Yes, we service Ola, Ather, TVS iQube, and other electric two-wheelers at your doorstep in Noida." },
    { question: "Is there a warranty on the repair?", answer: "Yes, all repairs come with a 15-day labor warranty. If anything goes wrong with the same issue, we send a mechanic back at no extra charge." },
  ],
  roadside: {
    heading: "Noida Roadside Assistance",
    description: "Stranded on Yamuna Expressway, DND Flyway, or a sector road? A mechanic will come to your exact location with tools to fix the issue on the spot.",
  },
  finalCta: {
    heading: "Book doorstep bike repair in Noida.",
    description: "Verified mechanic at your home or office across Sector 18, 62, 137, 150 & all Noida sectors. Starting ₹550.",
  },
};

export function NoidaSections(props: Omit<CityPageSectionsProps, "config">) {
  return <CityPageSections config={noidaConfig} {...props} />;
}
