/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: '**.fixwheel.app',
      },
      {
        protocol: 'https',
        hostname: 'secure.gravatar.com',
      },
      {
        protocol: 'https',
        hostname: '**.google.com',
      },
    ],
  },
  async redirects() {
    return [
      {
        source: '/services/electric-scooter-repair',
        destination: '/electric-vehicle',
        statusCode: 301,
      },
      // 301: preserve the exact legacy 404 URLs reported in the October 2 crawl.
      // These brand/model combinations were generated by old brand aliases; send
      // them to the authoritative model pages instead of publishing duplicates.
      {
        source: '/:legacyBrand(okinawa|ampere|bounce)/:model(roadster-x|s1-air|s1-x-4-kwh|s1-x-3-kwh|roadster-pro|s1-x|s1-x-2-kwh|s1-pro-gen-2|roadster)',
        destination: '/ola-electric/:model',
        statusCode: 301,
      },
      {
        source: '/ultraviolette/:model(rc-200|250-duke|rc-390|rc-125|390-adventure|250-adventure|125-duke|390-adventure-x|890-duke-r|200-duke|390-duke)',
        destination: '/ktm/:model',
        statusCode: 301,
      },
      {
        source: '/vida/:model(karizma-xmr|glamour|pleasure-plus|super-splendor|xtreme-200r|passion-plus|hf-deluxe|xpulse-200-4v-200t|xtreme-160r-4v|karizma-zmr-r|xoom-110|splendor-pro-ismart|destini-125|hf-100|cd-deluxe-cd-dawn|passion-pro|glamour-xtec|splendor-xtec|xtreme-125r|super-splendor-xtec|xtreme-200s-4v|mavrick-440|splendor-plus|passion-xtec|maestro-edge-110-125)',
        destination: '/hero/:model',
        statusCode: 301,
      },
      {
        source: '/tork/:model(rv300|rv400|rv400-brz|rv1)',
        destination: '/revolt/:model',
        statusCode: 301,
      },
      {
        source: '/vida-hero-',
        destination: '/vida-hero',
        statusCode: 301,
      },
      {
        source: '/other-brand-ev-',
        destination: '/other-brand-ev',
        statusCode: 301,
      },
      {
        source: '/tvs-ev-',
        destination: '/tvs-ev',
        statusCode: 301,
      },
      {
        source: '/bajaj-ev-',
        destination: '/bajaj-ev',
        statusCode: 301,
      },
      {
        source: '/gurgaon/dlf-phases',
        destination: '/gurgaon/dlf-phase-1',
        statusCode: 301,
      },
      // 301: legacy service and bike-type URLs -> city-first canonical URLs
      {
        source: '/:city(delhi|gurgaon|noida|ghaziabad|faridabad)/commuter-bike-service',
        destination: '/:city/bike',
        statusCode: 301,
      },
      {
        source: '/services/commuter-bike-service/:city(delhi|gurgaon|noida|ghaziabad|faridabad)',
        destination: '/:city/bike',
        statusCode: 301,
      },
      {
        source: '/commuter-bike-service/:city(delhi|gurgaon|noida|ghaziabad|faridabad)',
        destination: '/:city/bike',
        statusCode: 301,
      },
      {
        source: '/services/:bikeType(scooty-repair|commuter-bike-service|sports-bike-service|premium-bike-service)/:city(delhi|gurgaon|noida|ghaziabad|faridabad)',
        destination: '/:city/:bikeType',
        statusCode: 301,
      },
      {
        source: '/services/:service/:city(delhi|gurgaon|noida|ghaziabad|faridabad)',
        destination: '/:city/services/:service',
        statusCode: 301,
      },
      {
        source: '/:bikeType(scooty-repair|commuter-bike-service|sports-bike-service|premium-bike-service)/:city(delhi|gurgaon|noida|ghaziabad|faridabad)',
        destination: '/:city/:bikeType',
        statusCode: 301,
      },
      // 301 Permanent Redirects for removed/deprecated service URLs
      {
        source: '/services/obd-scanner',
        destination: '/electric-vehicle',
        permanent: true,
      },
      {
        source: '/services/obd-scanner/:path*',
        destination: '/electric-vehicle',
        permanent: true,
      },
      {
        source: '/services/pick-and-drop',
        destination: '/services',
        permanent: true,
      },
      {
        source: '/services/pick-and-drop/:path*',
        destination: '/services',
        permanent: true,
      },
      // 301 Permanent Redirect for all deprecated partner city & locality sub-pages to main /partner
      {
        source: '/partner/:path+',
        destination: '/partner',
        permanent: true,
      },
      // 301 Permanent Redirect for all deprecated book brand sub-pages (e.g. /book/hero) to /book
      {
        source: '/book/:brand((?!checkout$).*)',
        destination: '/book',
        permanent: true,
      },
      // 301 Permanent Redirects for sports bike service pages (moved to root /sports-bike-service, locality pages removed)
      {
        source: '/services/sports-bike-service',
        destination: '/sports-bike-service',
        permanent: true,
      },
      {
        source: '/services/sports-bike-service/:city(gurgaon|delhi|noida|ghaziabad|faridabad)',
        destination: '/sports-bike-service/:city',
        permanent: true,
      },
      {
        source: '/services/sports-bike-service/:city/:locality+',
        destination: '/sports-bike-service/:city',
        permanent: true,
      },
      {
        source: '/sports-bike-service/:city/:locality+',
        destination: '/sports-bike-service/:city',
        permanent: true,
      },
      {
        source: '/services/sports-bike-service/:path*',
        destination: '/sports-bike-service',
        permanent: true,
      },
      // 301 Permanent Redirects to the canonical EV service route
      {
        source: '/electric-scooter-repair',
        destination: '/electric-vehicle',
        statusCode: 301,
      },
      {
        source: '/services/ev-service/:city(gurgaon|delhi|noida|ghaziabad|faridabad)',
        destination: '/:city/services/electric-scooter-repair',
        statusCode: 301,
      },
      {
        source: '/:city(gurgaon|delhi|noida|ghaziabad|faridabad)/services/ev-service',
        destination: '/:city/services/electric-scooter-repair',
        statusCode: 301,
      },
      {
        source: '/services/ev-service',
        destination: '/electric-vehicle',
        statusCode: 301,
      },
      {
        source: '/electric-scooter-repair/:city(gurgaon|delhi|noida|ghaziabad|faridabad)',
        destination: '/:city/services/electric-scooter-repair',
        statusCode: 301,
      },
      {
        source: '/:city(gurgaon|delhi|noida|ghaziabad|faridabad)/electric-scooter-repair',
        destination: '/:city/services/electric-scooter-repair',
        statusCode: 301,
      },
      {
        source: '/services/electric-scooter-repair/:city(gurgaon|delhi|noida|ghaziabad|faridabad)',
        destination: '/:city/services/electric-scooter-repair',
        statusCode: 301,
      },
      {
        source: '/electric-scooter-repair/:city/:locality+',
        destination: '/:city/services/electric-scooter-repair',
        statusCode: 301,
      },
      {
        source: '/services/electric-scooter-repair/:city/:locality+',
        destination: '/:city/services/electric-scooter-repair',
        statusCode: 301,
      },
      {
        source: '/services/ev-service/:path+',
        destination: '/electric-vehicle',
        statusCode: 301,
      },
      // Retired Royal Enfield service URLs go directly to the canonical brand page.
      {
        source: '/royal-enfield-service/:path*',
        destination: '/royal-enfield',
        statusCode: 301,
      },
      {
        source: '/services/royal-enfield-service/:path*',
        destination: '/royal-enfield',
        statusCode: 301,
      },
      // Bike landing and city pages use the /bike URL family.
      {
        source: '/bike/:city(gurgaon|delhi|noida|ghaziabad|faridabad)',
        destination: '/:city/bike',
        statusCode: 301,
      },
      {
        source: '/commuter-bike-service',
        destination: '/bike',
        statusCode: 301,
      },
      {
        source: '/commuter-bike-service/:city(gurgaon|delhi|noida|ghaziabad|faridabad)',
        destination: '/:city/bike',
        statusCode: 301,
      },
      {
        source: '/services/commuter-bike-service',
        destination: '/bike',
        statusCode: 301,
      },
      {
        source: '/services/commuter-bike-service/:city(gurgaon|delhi|noida|ghaziabad|faridabad)',
        destination: '/:city/bike',
        permanent: true,
      },
      {
        source: '/services/commuter-bike-service/:city/:locality+',
        destination: '/:city/bike',
        permanent: true,
      },
      {
        source: '/commuter-bike-service/:city/:locality+',
        destination: '/:city/bike',
        permanent: true,
      },
      {
        source: '/services/commuter-bike-service/:path*',
        destination: '/bike',
        permanent: true,
      },
      // 301 Permanent Redirects for Scooty repair pages (moved to root /scooty-repair, locality pages removed)
      {
        source: '/services/scooty-repair',
        destination: '/scooty-repair',
        permanent: true,
      },
      {
        source: '/services/scooty-repair/:city(gurgaon|delhi|noida|ghaziabad|faridabad)',
        destination: '/scooty-repair/:city',
        permanent: true,
      },
      {
        source: '/services/scooty-repair/:city/:locality+',
        destination: '/scooty-repair/:city',
        permanent: true,
      },
      {
        source: '/scooty-repair/:city/:locality+',
        destination: '/scooty-repair/:city',
        permanent: true,
      },
      {
        source: '/services/scooty-repair/:path*',
        destination: '/scooty-repair',
        permanent: true,
      },
      // 301 Permanent Redirects for Premium Bike service pages (moved to root /premium-bike-service, locality pages removed)
      {
        source: '/services/premium-bike-service',
        destination: '/premium-bike-service',
        permanent: true,
      },
      {
        source: '/services/premium-bike-service/:city(gurgaon|delhi|noida|ghaziabad|faridabad)',
        destination: '/premium-bike-service/:city',
        permanent: true,
      },
      {
        source: '/services/premium-bike-service/:city/:locality+',
        destination: '/premium-bike-service/:city',
        permanent: true,
      },
      {
        source: '/premium-bike-service/:city/:locality+',
        destination: '/premium-bike-service/:city',
        permanent: true,
      },
      {
        source: '/services/premium-bike-service/:path*',
        destination: '/premium-bike-service',
        permanent: true,
      },
      // 301 Permanent Redirect for Basic service locality pages (locality pages removed, city pages kept under /services/basic-service/:city)
      {
        source: '/services/basic-service/:city/:locality+',
        destination: '/services/basic-service/:city',
        permanent: true,
      },
      // 301 Permanent Redirect for Oil Change locality pages (locality pages removed, city pages kept under /services/oil-change/:city)
      {
        source: '/services/oil-change/:city/:locality+',
        destination: '/services/oil-change/:city',
        permanent: true,
      },
      // 301 Permanent Redirect for Comprehensive Service locality pages (locality pages removed, city pages kept under /services/comprehensive-service/:city)
      {
        source: '/services/comprehensive-service/:city/:locality+',
        destination: '/services/comprehensive-service/:city',
        permanent: true,
      },
      // 301 Permanent Redirect for Engine Repair locality pages (locality pages removed, city pages kept under /services/engine-repair/:city)
      {
        source: '/services/engine-repair/:city/:locality+',
        destination: '/services/engine-repair/:city',
        permanent: true,
      },
      // 301 Permanent Redirect for Battery Replacement locality pages (locality pages removed, city pages kept under /services/battery-replacement/:city)
      {
        source: '/services/battery-replacement/:city/:locality+',
        destination: '/services/battery-replacement/:city',
        permanent: true,
      },
      // 301 Permanent Redirect for Brake Repair locality pages (locality pages removed, city pages kept under /services/brake-repair/:city)
      {
        source: '/services/brake-repair/:city/:locality+',
        destination: '/services/brake-repair/:city',
        permanent: true,
      },
      // 301 Permanent Redirects for non-offered services (Tyre Replacement -> /pricing, General Washing -> /services/basic-service)
      {
        source: '/services/tyre-replacement',
        destination: '/pricing',
        permanent: true,
      },
      {
        source: '/services/tyre-replacement/:path*',
        destination: '/pricing',
        permanent: true,
      },
      {
        source: '/services/general-washing',
        destination: '/services/basic-service',
        permanent: true,
      },
      {
        source: '/services/general-washing/:path*',
        destination: '/services/basic-service',
        permanent: true,
      },
      // 301 Permanent Redirects for legacy /brands/ URLs to clean root URLs
      {
        source: '/brands/:brand',
        destination: '/:brand',
        permanent: true,
      },
      {
        source: '/brands/:brand/:model',
        destination: '/:brand/:model',
        permanent: true,
      },
    ];
  },
};

export default nextConfig;
