import { NextResponse } from 'next/server';

export const dynamic = 'force-static';

export async function GET() {
  return new NextResponse(`<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://www.fixwheel.app</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>weekly</changefreq>
    <priority>1.0</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/about</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.5</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/author/sanjay-kumar</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.5</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/author/zakir-hussain</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.5</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/blog/bike-engine-oil-guide</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.6</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/blog/carburetor-vs-fi-maintenance</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.6</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/blog/disc-vs-drum-brake-maintenance</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.6</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/blog/electric-scooter-battery-care</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.6</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/blog/monsoon-bike-care-tips</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.6</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/blog/motorcycle-chain-maintenance-guide</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.6</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/book</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.5</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/book/checkout</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.5</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/confirmation</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.5</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/contact</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.5</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/delete-account</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.5</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/faq</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.5</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/partner</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.5</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/privacy-policy</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.5</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/process</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.5</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/terms</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.5</priority>
  </url>
</urlset>`, {
    headers: {
      'Content-Type': 'application/xml',
      'Cache-Control': 'public, max-age=3600, s-maxage=86400',
    },
  });
}
