import { NextResponse } from 'next/server';

export const dynamic = 'force-static';

export async function GET() {
  return new NextResponse(`<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://www.fixwheel.app/brands</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/brands/aprilia</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/brands/ather</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/brands/bajaj</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/brands/benelli</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/brands/harley-davidson</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/brands/hero</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/brands/honda</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/brands/jawa</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/brands/kawasaki</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/brands/ktm</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/brands/ola-electric</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/brands/royal-enfield</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/brands/suzuki</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/brands/tvs</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/brands/vespa</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/brands/yamaha</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/services/commuter-bike-service</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/services/electric-scooter-repair</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/services/premium-bike-service</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/services/royal-enfield-service</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/services/scooty-repair</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.fixwheel.app/services/sports-bike-service</loc>
    <lastmod>2026-07-25T19:39:55+00:00</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>
</urlset>`, {
    headers: {
      'Content-Type': 'application/xml',
      'Cache-Control': 'public, max-age=3600, s-maxage=86400',
    },
  });
}
