import CityPageSections, { type CityPageConfig, type CityPageSectionsProps } from "@/components/city/CityPageSections";

const gurgaonConfig: CityPageConfig = {
  cityName: "Gurgaon",
  citySlug: "gurgaon",
  hero: {
    eyebrow: "Doorstep bike mechanic · Gurgaon",
    title: "Doorstep Bike Repair Service",
    emphasis: "in Gurgaon",
    lead: "FixWheel offers doorstep bike repair service in Gurgaon. A verified mechanic will come to your home, office, or anywhere you are stranded to fix your bike or scooter. No need to visit a garage or wait in lines.",
    bookingLabel: "Book a Mechanic in Gurgaon →",
    arrivalTime: "45 min",
    ratingSource: "public-stats",
    serviceArea: "All sectors",
    ticketId: "FW-GGN-1042",
    ticketRows: [
      { label: "Service", value: "Basic Service" },
      { label: "Model", value: "Honda Activa" },
      { label: "Location", value: "Gurgaon" },
      { label: "Mechanic", value: "Verified ✓" },
      { label: "Warranty", value: "15 days" },
      { label: "Response", value: "29 min" },
    ],
    totalPaid: "₹550",
    ticketRegion: "GURUGRAM · NCR",
  },
  coverage: {
    heading: "We cover all areas of Gurgaon",
    description: "We dispatch mechanics across all Gurgaon sectors. A mechanic can usually reach you within 45 minutes.",
    expansionLabel: "📍 + All of Gurgaon covered",
    expansionStyle: "filled",
    areas: [
      { name: "DLF Phase 1", slug: "dlf-phase-1" },
      { name: "DLF Phase 2", slug: "dlf-phase-2" },
      { name: "DLF Phase 3", slug: "dlf-phase-3" },
      { name: "DLF Phase 4", slug: "dlf-phase-4" },
      { name: "DLF Phase 5", slug: "dlf-phase-5" },
      { name: "Sushant Lok", slug: "sushant-lok" },
      { name: "Golf Course Road", slug: "golf-course-road" },
      { name: "Sohna Road", slug: "sohna-road" },
      { name: "Palam Vihar", slug: "palam-vihar" },
      { name: "Udyog Vihar", slug: "udyog-vihar" },
      { name: "Dwarka Expressway", slug: "dwarka-expressway" },
      { name: "MG Road", slug: "mg-road" },
      { name: "Cyber City", slug: "cyber-city" },
      { name: "South City 1", slug: "south-city-1" },
      { name: "South City 2", slug: "south-city-2" },
      { name: "Nirvana Country", slug: "nirvana-country" },
      { name: "Sector 14", slug: "sector-14" },
      { name: "Sector 15", slug: "sector-15" },
      { name: "Sector 17", slug: "sector-17" },
      { name: "Sector 23", slug: "sector-23" },
      { name: "Sector 31", slug: "sector-31" },
      { name: "Sector 40", slug: "sector-40" },
      { name: "Sector 45", slug: "sector-45" },
      { name: "Sector 46", slug: "sector-46" },
      { name: "Sector 47", slug: "sector-47" },
      { name: "Sector 49", slug: "sector-49" },
      { name: "Sector 50", slug: "sector-50" },
      { name: "Sector 56", slug: "sector-56" },
      { name: "Sector 57", slug: "sector-57" },
      { name: "Sector 58", slug: "sector-58" },
      { name: "Ashok Vihar Phase 3", slug: "ashok-vihar-phase-3" },
      { name: "Huda City Centre", slug: "huda-city-centre" },
      { name: "Manesar", slug: "manesar" },
      { name: "Bhondsi", slug: "bhondsi" },
      { name: "Badshahpur", slug: "badshahpur" },
    ],
  },
  why: {
    heading: "How we work in Gurgaon",
    description: "Avoid traffic and long waits. Get your bike serviced at home or office without pushing it to a shop.",
    cards: [
      { title: "We come to you", text: "Our mechanic will visit your home, office, or any location in Gurgaon. You do not have to move your bike." },
      { title: "Trained mechanics", text: "All our mechanics are trained, verified, and background-checked before joining the platform." },
      { title: "Fixed pricing", text: "We give you a clear price before we start working. There are no hidden fees or surprise costs." },
      { title: "Fast arrival", text: "Our mechanics are spread across Gurgaon so we can reach you quickly, usually within 45 minutes." },
    ],
  },
  servicesHeading: "Bike Repair & Service Packages in Gurgaon",
  vehicles: {
    heading: "We service all bikes and scooters",
    description: "We repair all two-wheelers including daily scooters, commuter bikes, and electric vehicles.",
    types: [
      "🛵 Scooter",
      "🏍️ Bike",
      "⚡ EV Scooter",
      "⚡ EV Bike",
      "🏁 Sports Bike",
      "🔵 Royal Enfield",
      "+ all other types",
    ],
    brandsHeading: "Serviced in Gurgaon, whatever you ride",
    brands: [
      { name: "Royal Enfield", domain: "royalenfield.com" },
      { name: "Honda", domain: "honda.com" },
      { name: "Yamaha", domain: "yamahamotorsports.com" },
      { name: "Suzuki", domain: "suzukicycles.com" },
      { name: "KTM", domain: "ktm.com" },
      { name: "Bajaj", domain: "bajajauto.com" },
      { name: "TVS", domain: "tvsmotor.com" },
      { name: "Hero", domain: "heromotocorp.com" },
      { name: "Vespa", domain: "vespa.com" },
      { name: "Ola Electric", domain: "olaelectric.com" },
      { name: "Ather", domain: "atherenergy.com" },
      { name: "Jawa", domain: "jawa.in" },
      { name: "Aprilia", domain: "aprilia.com" },
      { name: "Harley-Davidson", domain: "harley-davidson.com" },
      { name: "Kawasaki", domain: "kawasakimotorcycle.com" },
      { name: "Benelli", domain: "benelli.com" },
    ],
  },
  howHeading: "4 steps from booking to a fixed bike",
  how: [
    { title: "1. Book a slot", text: "Pick your service and choose a time on our app or website." },
    { title: "2. Mechanic assigned", text: "We assign a verified mechanic near you." },
    { title: "3. Service at your doorstep", text: "The mechanic repairs your bike at your home or office." },
    { title: "4. Pay and rate", text: "Pay the fixed price online or cash and rate the mechanic." },
  ],
  reviews: {
    heading: "What our customers say",
    rating: "4.7★",
    items: [
      { text: "Quoted the price before starting, no extra charges added later. Honest service.", author: "Priya S. — Gurgaon" },
      { text: "Bike broke down near Cyber Hub. Mechanic arrived in 15 minutes and didn't overcharge for the emergency call.", author: "Rahul Sharma — Gurgaon" },
      { text: "Used them for my Royal Enfield. Genuine parts used and the engine feels noticeably smoother now.", author: "Vikram Singh — Gurgaon" },
    ],
  },
  partner: {
    heading: "Are you a bike mechanic in Gurgaon?",
    description: "Join our team of mechanics in Gurgaon. Work on your own schedule, get more customers, and grow your income.",
    registrationText: "Sign up in a few minutes and start getting service requests in your area.",
    benefits: [
      "Flexible working hours",
      "Easy booking management",
      "Receive service requests from customers in your area",
    ],
  },
  faqs: [
    { question: "How long does doorstep bike service take in Gurgaon?", answer: "Most repairs take 30 to 50 minutes. We tell you the time needed before we start." },
    { question: "How much does doorstep bike service cost in Gurgaon?", answer: "Service starts from ₹550 depending on your bike model. We give you a clear price before starting." },
    { question: "Which areas do you cover in Gurgaon?", answer: "We cover all areas and sectors in Gurgaon." },
    { question: "Can I book emergency roadside assistance in Gurgaon?", answer: "Yes, our roadside assistance is available 24/7 in Gurgaon." },
    { question: "Do you service Royal Enfield bikes at home in Gurgaon?", answer: "Yes, we repair and service all Royal Enfield models at your home." },
    { question: "Is there a warranty on the repair?", answer: "Yes, we provide a 15-day warranty on our service." },
  ],
  contact: {
    heading: "Contact us",
    description: "Have a question? We are available from 8 AM to 8 PM.",
    callNote: "Call us between 8AM and 8PM",
  },
  roadside: {
    heading: "Gurgaon Roadside Assistance",
    description: "Stranded on the road or have a breakdown in Gurgaon? A mechanic will come to your location with tools to fix your bike or scooter on the spot.",
    badgeColor: "#FFFFFF",
  },
  cityLinks: [
    { href: "/gurgaon", label: "Gurgaon / Gurugram" },
    { href: "/delhi", label: "Delhi" },
    { href: "/noida", label: "Noida" },
    { href: "/ghaziabad", label: "Ghaziabad" },
    { href: "/faridabad", label: "Faridabad" },
  ],
  finalCta: {
    heading: "Book doorstep bike repair in Gurgaon.",
    description: "Verified mechanic at your home or office, anywhere in Gurugram. Starting ₹550. No garage visit needed.",
  },
};

export function GurgaonSections(props: Omit<CityPageSectionsProps, "config">) {
  return <CityPageSections config={gurgaonConfig} {...props} />;
}
