import CityPageSections, { type CityPageConfig, type CityPageSectionsProps } from "@/components/city/CityPageSections";

const faridabadConfig: CityPageConfig = {
  cityName: "Faridabad",
  citySlug: "faridabad",
  hero: {
    eyebrow: "Bike mechanic at your doorstep · Faridabad",
    title: "Bike Mechanic Near Me",
    emphasis: "in Faridabad",
    lead: "FixWheel sends verified mobile mechanics directly to your house driveway, society parking lot, or office basement across Faridabad. No more pushing your broken motorcycle to local workshops — we carry the parts and tools to fix it on-site.",
    bookingLabel: "Book a Mechanic in Faridabad →",
    arrivalTime: "45 min",
    ratingSource: "public-stats",
    serviceArea: "Faridabad NCR",
    ticketId: "FW-FDB-0329",
    ticketRows: [
      { label: "Service", value: "Basic Service + Oil" },
      { label: "Model", value: "TVS Jupiter 125" },
      { label: "Location", value: "Sector 15, Faridabad" },
      { label: "Mechanic", value: "Verified ✓" },
      { label: "Warranty", value: "15 days" },
      { label: "Response", value: "38 min" },
    ],
    totalPaid: "₹999",
    ticketRegion: "FARIDABAD · NCR",
  },
  coverage: {
    description: "We serve all major sectors, residential enclaves, and industrial areas across Faridabad. Select your locality below for detailed street coverage.",
    expansionLabel: "📍 + Expanding across Faridabad",
    areas: [
      { name: "NIT Faridabad", slug: "nit-faridabad" },
      { name: "Sector 7", slug: "sector-7" },
      { name: "Sector 8", slug: "sector-8" },
      { name: "Sector 9", slug: "sector-9" },
      { name: "Sector 10", slug: "sector-10" },
      { name: "Sector 11", slug: "sector-11" },
      { name: "Sector 12", slug: "sector-12" },
      { name: "Sector 14", slug: "sector-14" },
      { name: "Sector 15", slug: "sector-15" },
      { name: "Sector 16", slug: "sector-16" },
      { name: "Sector 17", slug: "sector-17" },
      { name: "Sector 19", slug: "sector-19" },
      { name: "Sector 21", slug: "sector-21" },
      { name: "Sector 22", slug: "sector-22" },
      { name: "Sector 23", slug: "sector-23" },
      { name: "Sector 28", slug: "sector-28" },
      { name: "Sector 29", slug: "sector-29" },
      { name: "Sector 31", slug: "sector-31" },
      { name: "Sector 37", slug: "sector-37" },
      { name: "Sector 46", slug: "sector-46" },
      { name: "Sector 55", slug: "sector-55" },
      { name: "Sector 56", slug: "sector-56" },
      { name: "Sector 86", slug: "sector-86" },
      { name: "Sector 88", slug: "sector-88" },
      { name: "Sector 89", slug: "sector-89" },
      { name: "Old Faridabad", slug: "old-faridabad" },
      { name: "Ballabhgarh", slug: "ballabhgarh" },
      { name: "Tigaon Road", slug: "tigaon-road" },
      { name: "Suraj Kund", slug: "suraj-kund" },
      { name: "Mewla Maharajpur", slug: "mewla-maharajpur" },
      { name: "BK Chowk", slug: "bk-chowk" },
      { name: "Bata Chowk", slug: "bata-chowk" },
      { name: "YMCA Chowk", slug: "ymca-chowk" },
    ],
  },
  why: {
    heading: "Professional service right in your driveway",
    description: "From NIT markets to residential sectors, our mechanics coordinate directly to service your two-wheeler while you relax at home.",
    cards: [
      { title: "On-site doorstep servicing", text: "We perform all servicing, oil changes, and repairs directly in your parking area, driveway, or office basement." },
      { title: "Verified, trained mechanics", text: "Every technician is background-checked, trained, and accountable, giving you complete safety and quality mechanical work." },
      { title: "Transparent itemized billing", text: "No surprise bills or hidden margins. You review and approve the exact quote before the service begins." },
      { title: "15-day service guarantee", text: "All doorstep work and mechanical tuning are backed by our standard 15-day labor warranty for complete peace of mind." },
    ],
  },
  how: [
    { title: "1. Pick a service", text: "Select what your bike needs and pick a time slot on our app or website." },
    { title: "2. Mechanic dispatched", text: "A verified mechanic near your location in Faridabad is assigned and heads to you." },
    { title: "3. Repaired on-site", text: "Your bike is fixed right where it is parked — home, office, or society parking." },
    { title: "4. Pay and rate", text: "Pay the quoted amount via UPI, card, or cash, then rate the mechanic." },
  ],
  reviews: {
    heading: "From Faridabad riders",
    rating: "4.7★",
    reviewCount: "473+ reviews",
    items: [
      { text: "Excellent experience in Sector 15. The mechanic coordinate with my society guard and finished the basic service in the driveway under 45 minutes. Clean and hassle-free.", author: "Abhishek M. — Sector 15" },
      { text: "My Pulsar broke down near Bata Chowk during the rush hour. The emergency roadside assistance mechanic was there in 45 minutes, changed the clutch cable, and got me moving.", author: "Rohit S. — Bata Chowk" },
      { text: "Very professional service for my TVS Jupiter in NIT Faridabad. Upfront pricing, genuine oil, and no hidden margins. Highly recommend FixWheel.", author: "Sneha K. — NIT Faridabad" },
    ],
  },
  partner: {
    heading: "Are you a bike mechanic in Faridabad?",
    description: "Join the FixWheel network and receive bookings from riders in Faridabad. Set your own hours and manage everything from your phone.",
    registrationText: "Register in a few minutes and start receiving service requests in Faridabad.",
  },
  faqs: [
    { question: "How quickly can a mechanic reach me in Faridabad?", answer: "In most Faridabad sectors and NIT areas, our mechanics arrive within 45 minutes of booking confirmation." },
    { question: "What does doorstep bike repair cost in Faridabad?", answer: "Basic service starts from ₹550 depending on your bike model. We confirm the exact price before starting any work." },
    { question: "Which areas in Faridabad does FixWheel cover?", answer: "We cover all major Faridabad sectors (Sector 15, 16, 21, 37, 86, etc.) as well as NIT, Old Faridabad, Ballabhgarh, and Suraj Kund." },
    { question: "Do you offer emergency roadside help in Faridabad?", answer: "Yes, we dispatch mechanics for roadside breakdowns across our Faridabad service area, including Mathura Road and Suraj Kund Road. Available 24/7." },
    { question: "Is there a warranty on the repair?", answer: "Yes, all repairs come with a 15-day labor warranty. If anything goes wrong with the same issue, we send a mechanic back at no extra charge." },
  ],
  roadside: {
    heading: "Faridabad Roadside Assistance",
    description: "Stranded on Mathura Road, Suraj Kund Road, or near Bata Chowk? A mechanic will come to your exact location with tools to fix the issue on the spot.",
  },
  cityLinks: [
    { href: "/gurgaon", label: "Gurgaon / Gurugram" },
    { href: "/delhi", label: "Delhi" },
    { href: "/noida", label: "Noida" },
    { href: "/ghaziabad", label: "Ghaziabad" },
    { href: "/faridabad", label: "Faridabad" },
  ],
  finalCta: {
    heading: "Book doorstep bike repair in Faridabad.",
    description: "Verified mechanic at your home or office across NIT, Sector 15, 16, 17, 21, 37, 86 & all Faridabad areas. Starting ₹550.",
  },
};

export function FaridabadSections(props: Omit<CityPageSectionsProps, "config">) {
  return <CityPageSections config={faridabadConfig} {...props} />;
}
